# Generated by Django 4.0.2 on 2022-02-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='trim_season',
            field=models.CharField(choices=[('SUM', 'Summer'), ('SPG', 'Spring'), ('FLL', 'Fall'), ('WIN', 'Winter'), ('NAN', 'None')], default='SUM', max_length=3),
        ),
    ]
