# Generated by Django 4.0.2 on 2022-02-22 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_plant_trim_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('Tree', 'Tree'), ('Shrub', 'Shrub'), ('Vine', 'Vine'), ('Perin', 'Perineal'), ('Palm', 'Palm'), ('Annuals', 'Annuals')], default='Tree', max_length=15),
        ),
    ]
